### GET ALL USERS
GET http://localhost:5000/api/users


### GET USER BY ID
GET http://localhost:5000/api/users/6471134f0cb534c7d4137552


### CREATE USER
POST http://localhost:5000/api/users
Content-Type: application/json

{
   "name": "smithth",
   "email":"john99@email.com",
   "password": "P@ssw0rd"
}

### LOGIN USER
POST http://localhost:5000/api/login
Content-Type: application/json

{
   "email":"john99@email.com",
   "passwordd": "P@ssw0rd",
   "password": "password"
}

### UPADATE USER
PUT http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2NjMmU0ZTY2NGYyNjM4ZjMwMzQ3OSIsImFjY291bnRUeXBlIjoidXNlciIsImlhdCI6MTY4NTg5Nzk1Nn0.-pD4IxGBqP1wpRq_D1H3cSaOJcmVZOdMDohsTX_Qmas

{
   "name":"samsmith",
   "password": "P@ssw0rd"
}


### DELETE USER
DELETE http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcyZTIxZWU0ZmViZmQyOGY3ZDNkNCIsImlhdCI6MTY4NTUzMjE5M30.EwCpsH9Kg8L4R-X4FEKto-XCyLJk6qPcGVN4tNYHgrI
