### GET ALL USERS
GET http://localhost:5000/api/users


### GET USER BY ID
GET http://localhost:5000/api/users/6471134f0cb534c7d4137552


### CREATE USER
POST http://localhost:5000/api/users
Content-Type: application/json

{
   "email":"smith1234@email.com",
   "name": "smithth",
   "password": "Pa$$w0rd"
}

### LOGIN USER
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
   "email":"smith123@email.com",
   "password": "Pa$$w0rd"
}

### UPADATE USER
PUT http://localhost:5000/api/users/647350e59ba0b84f218f5145
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzM1MGU1OWJhMGI4NGYyMThmNTE0NSIsImlhdCI6MTY4NTI3ODk0OX0.G-DaVvYt9u4phy-m1idQp1UhesVJg-j1No-ju8t4uCU

{
   "name":"smith-updated",
   "email": "email-updated@email.com"
}

### DELETE USER
DELETE http://localhost:5000/api/users/647350e59ba0b84f218f5145
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzMwZGZmNDY5MjUzNjZkZWQ4Zjg1MyIsImlhdCI6MTY4NTI3OTI0N30.092dpezHP-_ZM-u1xJyGtZXenOD9cU_Dbcgu1DzP3Ak
