### GET ALL USERS
GET http://localhost:5000/api/users


### GET USER BY ID
GET http://localhost:5000/api/users/6471134f0cb534c7d4137552


### CREATE USER
POST http://localhost:5000/api/users
Content-Type: application/json

{
   "name": "smithth",
   "email":"john@email.com",
   "password": "P@ssw0rd"
}

### LOGIN USER
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email":"smith123@email.com",
   "password": "P@ssw0rd"
}

### UPADATE USER
PUT http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Nzc0MTFmNzZkZTAwNzFlNDkzMTk2NSIsImlhdCI6MTY4NTUzNzA1NX0.1thwInbvxPIwN80W_mA0uX17b0esaE7DBDt_Kv5WX5M

{
   "name":"smith-updated",
   "email": "email-updated@email.com"
}

### DELETE USER
DELETE http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzcyZTIxZWU0ZmViZmQyOGY3ZDNkNCIsImlhdCI6MTY4NTUzMjE5M30.EwCpsH9Kg8L4R-X4FEKto-XCyLJk6qPcGVN4tNYHgrI
